name: Deploying to Cloud Run 1.1

on:
    workflow_dispatch:
    push:
        branches:
            - "containerize"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Authenticate with Google Cloud
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: "${{ secrets.GG_CREDENTIAL }}"

            - name: Configure docker
              run: gcloud auth configure-docker us-east1-docker.pkg.dev

            - name: Build and push Backend docker image
              run: |
                  docker build -t us-east1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/iluvus/testing:latest \
                  --build-arg MONGODB_URI=$MONGODB_URI \
                  --build-arg MONGODB_DB=$MONGODB_DB \
                  --build-arg PROJECT_PASSWORDTOKEN=$PROJECT_PASSWORDTOKEN ./
                  docker push us-east1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/iluvus/testing:latest
              env:
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
                  MONGODB_DB: ${{ secrets.MONGODB_DB }}
                  PROJECT_PASSWORDTOKEN: ${{ secrets.PROJECT_PASSWORDTOKEN }}

    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Authenticate with Google Cloud
              uses: "google-github-actions/auth@v1"
              with:
                  credentials_json: "${{ secrets.GG_CREDENTIAL }}"

            - name: Deploy Backend to Cloud Run
              uses: "google-github-actions/deploy-cloudrun@v1"
              with:
                  project_id: ${{ secrets.PROJECT_ID }}
                  service: "${{ secrets.PROJECT_SERVICE }}"
                  region: "us-east1"
                  image: "us-east1-docker.pkg.dev/${{ secrets.PROJECT_ID }}/iluvus/testing:latest"
